feat: add virtual chip computing power splitting support
ZhuLegend/hw_dcmi pull request #1
Opened 2024-12-12 06:02 UTC by harkerhand

test all passed

# Notes
when don't know the vchip ID, `destroy_virtual_chip(u32)` need the `dcmi_get_device_info` , which has not been implemented yet

2024-12-12 10:56 UTC, ZhuLegend requested changes
- 在给C库提供binding的时候，不只考虑简单的替换所有函数名、变量，而是考虑怎么做才是符合Rust设计思想的，用类型系统表达的约束比在文档中表达有力的多；
- 既然Virtual Chip也有一个id，能否参考Device和Chip的定义，创建一个新类别VirtualChip来避免重复填Virtual Chip的ID？
- 请把rustfmt格式化代码的修改和算力切分接口的新增功能拆分成两个提交，可以先revert当前commit再重新push

2024-12-13 15:13 UTC, harkerhand commented on crates/hw_dcmi/src/structs.rs
> +impl From<&VChipRes> for ffi::dcmi_create_vdev_res_stru {
accepted

2024-12-17 07:03 UTC, ZhuLegend requested changes
设计接口的时候，可以参考一下[Rust API指南](https://rust-chinese-translation.github.io/api-guidelines/)

2024-12-17 07:03 UTC, ZhuLegend commented on crates/hw_dcmi/src/test/mod.rs
> +    let vchip_out = chip.create_virtual_chip(vchip_res).unwrap();
这一段相同代码重复了这么多次可以考虑写一个函数来直接创建并返回virtual_chip

2024-12-17 07:03 UTC, ZhuLegend commented on crates/hw_dcmi/src/test/mod.rs
> +    let dcmi = DCMI::init().unwrap();
DCMI::init在load_dynamic的情况下，会加载动态链接库，要避免反复加载，用LazyCell提供test mod内全局唯一的static版本

2024-12-17 08:29 UTC, harkerhand commented on crates/hw_dcmi/src/device.rs
> +    pub fn vfg_id(&self) -> u32 {
vfg_id表示指定虚拟设备所属的虚拟分组ID，猜测是Virtual Functional Group ID，**modified**

2024-12-17 09:10 UTC, harkerhand commented on crates/hw_dcmi/src/test/mod.rs
> +    let vchip_out = chip.create_virtual_chip(vchip_res).unwrap();
!TODO 暂时无法解决生命周期问题

2024-12-17 14:13 UTC, ZhuLegend requested changes

2024-12-17 14:13 UTC, ZhuLegend commented on crates/hw_dcmi/src/enums.rs
> +        DestroyVChipMode::AllDevices
emmm，我的意思是`SingleDeviceId`可以保留，因为它内部的字段是不是`pub`的，crate外用户无法绕过我们提供的`try_new`方法创建，`DestroyVChipMode`是`pub`的，如果SingleDevice内用u32，crate外用户可以直接通过`DestroyVChipMode::SingleDevice(65535)`构造参数非法的enum

single_device和all_devices应该是pub的方法，前者可以在函数内部调用SingleDeviceId的try_new方法来获得SingleDeviceId，这样用户构造enum的语句就从`DestroyVChipMode::SingleDevice(SingleDeviceId::try_new(id))`变成`DestroyVChipMode::single_device(id)`了，更简单一点

2024-12-17 14:13 UTC, ZhuLegend commented on crates/hw_dcmi/src/enums.rs
> +        DestroyVChipMode::AllDevices
而且既然内部报错是目标，那叫Mode合适吗？还是叫Target更符合语义一点？

2024-12-21 06:29 UTC, harkerhand commented on crates/hw_dcmi/src/test/mod.rs
> +static DCMI_INSTANCE: Lazy<DCMI> = Lazy::new(|| DCMI::init().unwrap());
`LazyCell` 内部使用了 `UnsafeCell`，而 `UnsafeCell` 类型没有实现 `Sync`，可能需要为 `DCMI` 或者 `UnsafeCell<DCMI>` 实现sync?

2024-12-21 14:03 UTC, ZhuLegend commented on crates/hw_dcmi/src/test/mod.rs
> +static DCMI_INSTANCE: Lazy<DCMI> = Lazy::new(|| DCMI::init().unwrap());
参考官方文档`LazyCell的Sync版本是LazyLock`

2024-12-21 15:04 UTC, ZhuLegend reviewed
Good Job

2024-12-21 15:06 UTC, ZhuLegend reviewed
Ok

2024-12-21 15:07 UTC, ZhuLegend approved these changes
Good Job

2024-12-21 15:08 UTC, merged